from conexiones_bd import DAO8Escalones
from pregunta_comun import Pregunta_comun

bd=DAO8Escalones("8escalones.db") 
p=Pregunta_comun("Cine y Televisión", "¿Cuál fue la primera película de Disney?", "A) Blanca Nieves y los Siete Enanitos", "Normal", ["A) Blanca Nieves y los Siete Enanitos", "B) Pinocho", "C) Dumbo", "D) Fantasía"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿En qué año se estrenó 'El Padrino'?", "B) 1972", "Normal", ["A) 1970", "B) 1972", "C) 1974", "D) 1976"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Quién interpreta a Harry Potter en la saga de películas?", "A) Daniel Radcliffe", "Normal", ["A) Daniel Radcliffe", "B) Elijah Wood", "C) Tom Felton", "D) Rupert Grint"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál es el personaje principal de la serie 'Breaking Bad'?", "B) Walter White", "Normal", ["A) Saul Goodman", "B) Walter White", "C) Jesse Pinkman", "D) Hank Schrader"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Quién dirigió 'Jurassic Park'?", "B) Steven Spielberg", "Normal", ["A) George Lucas", "B) Steven Spielberg", "C) James Cameron", "D) Ridley Scott"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál de estos personajes es un villano en la saga de Star Wars?", "C) Darth Vader", "Normal", ["A) Luke Skywalker", "B) Han Solo", "C) Darth Vader", "D) Obi-Wan Kenobi"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Quién interpretó a Jack en la película 'Titanic'?", "C) Leonardo DiCaprio", "Normal", ["A) Matt Damon", "B) Brad Pitt", "C) Leonardo DiCaprio", "D) Tom Cruise"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál es el nombre del villano en 'Los Vengadores' (2012)?", "A) Loki", "Normal", ["A) Loki", "B) Thanos", "C) Ultron", "D) Magneto"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Qué serie popular presenta a un grupo de amigos que viven en Nueva York?", "A) Friends", "Normal", ["A) Friends", "B) How I Met Your Mother", "C) The Big Bang Theory", "D) Seinfeld"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿En qué película escuchamos la frase 'Hasta la vista, baby'?", "A) Terminator", "Normal", ["A) Terminator", "B) Depredador", "C) Commando", "D) Total Recall"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Qué director es conocido por su estilo de 'terror psicológico' en películas como Psicosis y Los Pájaros?", "A) Alfred Hitchcock", "Normal", ["A) Alfred Hitchcock", "B) Stanley Kubrick", "C) Roman Polanski", "D) Wes Craven"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál es la primera película de la saga de Marvel?", "B) Iron Man", "Normal", ["A) Capitán América", "B) Iron Man", "C) Thor", "D) Hulk"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Quién es el protagonista de la serie 'The Mandalorian'?", "C) Mando", "Normal", ["A) Han Solo", "B) Kylo Ren", "C) Mando", "D) Yoda"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Qué película animada de Disney-Pixar presenta a una niña llamada Riley y sus emociones?", "B) Intensa-Mente", "Normal", ["A) Valiente", "B) Intensa-Mente", "C) Up", "D) Toy Story"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Quién protagoniza 'La Máscara'?", "B) Jim Carrey", "Normal", ["A) Robin Williams", "B) Jim Carrey", "C) Mike Myers", "D) Adam Sandler"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál es la famosa canción de El guardaespaldas interpretada por Whitney Houston?", "A) I Will Always Love You", "Normal", ["A) I Will Always Love You", "B) I Have Nothing", "C) Run to You", "D) Queen of the Night"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál de estas películas ganó el Oscar a Mejor Película en 1994?", "A) Forrest Gump", "Normal", ["A) Forrest Gump", "B) Pulp Fiction", "C) Cadena Perpetua", "D) Cuatro Bodas y un Funeral"])
bd.alta_pregunta_normal(p)
p=Pregunta_comun("Cine y Televisión", "¿Cuál de estas películas está basada en una novela de Stephen King?", "A) El Resplandor", "Normal", ["A) El Resplandor", "B) Matrix", "C) Jurassic Park", "D) El Padrino"])
bd.alta_pregunta_normal(p)
